Develop pc bv2.0 mme016
lardc/hw-QrrtqSyncBoard pull request #4
Opened 2024-11-08 10:41 UTC by IgnatevA1

2024-11-08 11:00 UTC, asytyi requested changes

2024-11-08 11:00 UTC, asytyi commented on Firmware/Sources/Controller/Logic.c
> +	ScopeCurrentScaleResult = (Results[0].Irr < (EP_MIN_SCALE * 10)) ? EP_MIN_SCALE :
Переменную `ScopeCurrentScaleResult` можно объявить локально здесь, т.к. она больше нигде не используется

2024-11-08 11:00 UTC, asytyi commented on Firmware/Sources/Controller/Logic.c
> +		ScopeCurrentScaleResult = DC_Current;
А это присвоение ни на что не влияет, его можно прибить

2024-11-08 11:00 UTC, asytyi commented on Firmware/Sources/Controller/Logic.c
> +static Int16U K_Unit, DC_Current, DC_CurrentRiseRate, DC_NamberFallRate, DC_CurrentFallRate, ScopeCurrentScale, ScopeCurrentScaleResult;
И объявление здесь прибить

2024-11-12 12:23 UTC, asytyi requested changes

2024-11-12 12:23 UTC, asytyi commented on Firmware/Sources/Controller/Logic.c
> +								else if(Results[ResultsCounter].Irr > DC_Current * 11)
Почему умножение на 11?

2024-11-12 12:25 UTC, IgnatevA1 commented on Firmware/Sources/Controller/Logic.c
> +		ScopeCurrentScaleResult = DC_Current;
Это присвоение для 1 формирования, иначе там будет произвольное число

2024-11-12 13:17 UTC, IgnatevA1 commented on Firmware/Sources/Controller/Logic.c
> +	ScopeCurrentScaleResult = (Results[0].Irr < (EP_MIN_SCALE * 10)) ? EP_MIN_SCALE :
только переменная ScopeCurrentScale, а не ScopeCurrentScaleResult

2024-11-12 13:19 UTC, IgnatevA1 commented on Firmware/Sources/Controller/Logic.c
> +								else if(Results[ResultsCounter].Irr > DC_Current * 11)
Отладочная запись просочилась, из-за того что у нас Irr на КЗ больше прямого тока пришлось немного подправлять для снятия данных

2024-11-13 09:37 UTC, asytyi approved these changes

2024-12-24 12:02 UTC, asytyi approved these changes

2025-07-29 10:53 UTC, closed without merging